import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:assiist_front_end/theme/app_styles.dart';
import 'package:assiist_front_end/widgets/select_or_add_contact.dart';
import 'package:assiist_front_end/widgets/nav_bar_back_button.dart';
import 'package:assiist_front_end/core/models/contact.dart';
import 'package:assiist_front_end/core/models/reservation.dart';
import 'package:assiist_front_end/providers/auth_providers.dart';
import 'package:assiist_front_end/providers/reservation_providers.dart';

class ReservationScreen extends ConsumerStatefulWidget {
  const ReservationScreen({super.key});

  @override
  ConsumerState<ReservationScreen> createState() => _ReservationScreenState();
}

class _ReservationScreenState extends ConsumerState<ReservationScreen> {
  Contact? _selectedContact;
  bool _isLoading = false;
  final GlobalKey<SelectOrAddContactState> _selectOrAddContactKey =
      GlobalKey<SelectOrAddContactState>();

  void _onContactSelected(Contact contact) {
    setState(() {
      _selectedContact = contact;
    });
  }

  Future<void> _handleAddToPromoList() async {
    if (_selectedContact == null) return;

    setState(() => _isLoading = true);

    final userId = ref.read(userIdProvider);
    final accountId = ref.read(currentAccountIdProvider);

    if (userId == null || accountId == null) {
      if (mounted) {
        showCupertinoDialog(
          context: context,
          builder:
              (context) => CupertinoAlertDialog(
                title: const Text('Error'),
                content: const Text(
                  'User or account information not available',
                ),
                actions: [
                  CupertinoDialogAction(
                    child: AppStyles.accentText(context, 'OK'),
                    onPressed: () => Navigator.of(context).pop(),
                  ),
                ],
              ),
        );
      }
      setState(() => _isLoading = false);
      return;
    }

    // DEBUG: Check if reservation already exists before attempting to create
    try {
      print(
        '[DEBUG] Checking if reservation exists for contact: ${_selectedContact!.id}',
      );
      final existingReservations = await ref.read(
        getReservationsProvider({'contactId': _selectedContact!.id}).future,
      );
      print(
        '[DEBUG] Found ${existingReservations.length} existing reservations for this contact',
      );

      if (existingReservations.isNotEmpty) {
        print('[DEBUG] Existing reservation found - this explains the 409!');
        for (var reservation in existingReservations) {
          print(
            '[DEBUG] Existing reservation: ${reservation.id}, contact_id: ${reservation.contactId}, email: ${reservation.contactEmail}',
          );
        }

        if (mounted) {
          showCupertinoDialog(
            context: context,
            builder:
                (context) => CupertinoAlertDialog(
                  title: const Text('Already on List'),
                  content: Text(
                    'This contact is already on the founders list.\n\nContact ID: ${_selectedContact!.id}\nFound ${existingReservations.length} existing reservation(s).',
                  ),
                  actions: [
                    CupertinoDialogAction(
                      child: AppStyles.accentText(context, 'OK'),
                      onPressed: () => Navigator.of(context).pop(),
                    ),
                  ],
                ),
          );
        }
        setState(() => _isLoading = false);
        return;
      }
    } catch (e) {
      print('[DEBUG] Error checking existing reservations: $e');
    }

    final reservation = Reservation(
      id: '', // Will be generated by backend
      contactId: _selectedContact!.id,
      contactName: _selectedContact!.displayName,
      contactEmail: _selectedContact!.emails?.firstOrNull?.address,
      contactPhone: _selectedContact!.phone_numbers?.firstOrNull?.number,
      userId: userId,
      accountId: accountId,
      createdOn: DateTime.now(), // ← FIXED: Use *_on suffix
      updatedOn: DateTime.now(), // ← FIXED: Use *_on suffix
    );

    print(
      '[DEBUG] Attempting to create reservation for contact: ${_selectedContact!.id}',
    );
    print('[DEBUG] Contact name: ${_selectedContact!.displayName}');
    print('[DEBUG] Contact email: ${reservation.contactEmail}');

    final success = await ref.read(
      addToReservationListProvider(reservation).future,
    );

    if (!mounted) return;

    if (success) {
      showCupertinoDialog(
        context: context,
        builder:
            (context) => CupertinoAlertDialog(
              title: const Text('Success'),
              content: const Text('Contact added to reservation list'),
              actions: [
                CupertinoDialogAction(
                  child: AppStyles.accentText(context, 'OK'),
                  onPressed: () {
                    Navigator.of(context).pop();
                    // Pop back to dashboard
                    Navigator.pop(context, true);
                  },
                ),
              ],
            ),
      );
    } else {
      showCupertinoDialog(
        context: context,
        builder:
            (context) => CupertinoAlertDialog(
              title: const Text('Error'),
              content: const Text(
                'Failed to add contact to reservation list. This contact may already be on the list.',
              ),
              actions: [
                CupertinoDialogAction(
                  child: AppStyles.accentText(context, 'OK'),
                  onPressed: () => Navigator.of(context).pop(),
                ),
              ],
            ),
      );
      setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = CupertinoTheme.of(context);

    return CupertinoPageScaffold(
      backgroundColor: AppStyles.subtleBackgroundColor(context),
      navigationBar: CupertinoNavigationBar(
        backgroundColor: AppStyles.subtleBackgroundColor(context),
        leading: const NavBarBackButton(),
        middle: const Text(
          'Add to Founders List',
          style: TextStyle(color: CupertinoColors.white),
        ),
      ),
      child: SafeArea(
        bottom: false,
        child: Column(
          children: [
            Expanded(
              child: SingleChildScrollView(
                padding: const EdgeInsets.all(16.0),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    const SizedBox(height: 24.0),
                    Text(
                      'Select a contact to add to the founders list',
                      style: AppStyles.h2TextStyle(context),
                      textAlign: TextAlign.center,
                    ),
                    const SizedBox(height: 24.0),
                    SelectOrAddContact(
                      key: _selectOrAddContactKey,
                      onContactSelected: _onContactSelected,
                      showNavigateChevron: false,
                      showCreateButton: false,
                      showEditableFieldsOnSelect: false,
                    ),
                  ],
                ),
              ),
            ),
            Container(
              padding: const EdgeInsets.symmetric(
                horizontal: 16.0,
                vertical: 12.0,
              ).copyWith(bottom: MediaQuery.of(context).padding.bottom + 12.0),
              decoration: BoxDecoration(
                color: AppStyles.cardBackgroundColor(context),
                border: Border(
                  top: BorderSide(
                    color: CupertinoColors.separator.resolveFrom(context),
                    width: 0.5,
                  ),
                ),
              ),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  CupertinoButton(
                    padding: const EdgeInsets.symmetric(
                      horizontal: 20,
                      vertical: 10,
                    ),
                    onPressed: () => Navigator.pop(context),
                    child: AppStyles.accentText(
                      context,
                      'Cancel',
                      style: const TextStyle(
                        fontSize: 16.0,
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ),
                  CupertinoButton(
                    padding: EdgeInsets.zero,
                    onPressed:
                        _selectedContact != null && !_isLoading
                            ? _handleAddToPromoList
                            : null,
                    child: Container(
                      padding: AppStyles.filledButtonPadding,
                      decoration: AppStyles.accentButtonDecoration(
                        borderRadius: BorderRadius.circular(28.0),
                      ),
                      child:
                          _isLoading
                              ? const CupertinoActivityIndicator(
                                color: CupertinoColors.white,
                              )
                              : const Text(
                                'Add to Founders List',
                                style: TextStyle(
                                  color: CupertinoColors.white,
                                  fontSize: 16.0,
                                  fontWeight: FontWeight.w600,
                                ),
                              ),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
