import uuid
from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Field, EmailStr

# --- Nested Schemas (mirrors core models for now) ---

class AttendeeSchema(BaseModel):
    email: Optional[EmailStr] = None
    name: Optional[str] = None
    response_status: Optional[str] = None # e.g., accepted, declined, tentative, needsAction
    is_optional: Optional[bool] = False

    class Config:
        from_attributes = True

class AttachmentSchema(BaseModel):
    file_url: str
    mime_type: Optional[str] = None
    title: Optional[str] = None

    class Config:
        from_attributes = True

# --- Base Schema (Common Fields) ---

class AppointmentBaseSchema(BaseModel):
    external_id: Optional[str] = None
    calendar_provider: Optional[str] = Field(None, description="e.g., google, outlook, manual")
    title: Optional[str] = None
    description: Optional[str] = None
    start_time: Optional[datetime] = None
    end_time: Optional[datetime] = None
    timezone: Optional[str] = Field(None, description="IANA timezone name, e.g., America/New_York")
    is_all_day: bool = False
    location: Optional[str] = None
    organizer: Optional[AttendeeSchema] = None
    attendees: List[AttendeeSchema] = []
    attachments: List[AttachmentSchema] = []
    status: Optional[str] = Field(None, description="e.g., confirmed, tentative, cancelled")
    assiist_contact_ids: List[uuid.UUID] = Field([], description="Link to contacts in Assiist")
    source_account_id: Optional[str] = Field(None, description="Identifier for the specific linked account, e.g., google-123")
    needs_contact_creation_prompt: Optional[bool] = False # Allow setting this?

# --- Create Schema (for POST requests) ---

class AppointmentCreateSchema(AppointmentBaseSchema):
    # user_id will be injected from the auth token in the endpoint
    pass # Inherits all fields from Base

# --- Update Schema (for PATCH requests) ---

class AppointmentUpdateSchema(BaseModel):
    # All fields are optional for PATCH
    external_id: Optional[str] = None
    calendar_provider: Optional[str] = Field(None, description="e.g., google, outlook, manual")
    title: Optional[str] = None
    description: Optional[str] = None
    start_time: Optional[datetime] = None
    end_time: Optional[datetime] = None
    timezone: Optional[str] = Field(None, description="IANA timezone name, e.g., America/New_York")
    is_all_day: Optional[bool] = None
    location: Optional[str] = None
    organizer: Optional[AttendeeSchema] = None
    attendees: Optional[List[AttendeeSchema]] = None
    attachments: Optional[List[AttachmentSchema]] = None
    status: Optional[str] = Field(None, description="e.g., confirmed, tentative, cancelled")
    assiist_contact_ids: Optional[List[uuid.UUID]] = Field(None, description="Link to contacts in Assiist")
    source_account_id: Optional[str] = Field(None, description="Identifier for the specific linked account, e.g., google-123")
    needs_contact_creation_prompt: Optional[bool] = None
    processed_at: Optional[datetime] = None # Allow updating processed time?

# --- Response Schema (for GET requests) ---

class AppointmentResponseSchema(AppointmentBaseSchema):
    id: uuid.UUID # The internal ID generated by our system
    user_id: str  # The owner user ID

    # Include fields from Base plus read-only/generated fields
    created_at_source: Optional[datetime] = None
    updated_at_source: Optional[datetime] = None
    processed_at: Optional[datetime] = None

    class Config:
        from_attributes = True # Enable conversion from ORM/Pydantic models 