import uuid
from datetime import datetime
from typing import Optional, List

from pydantic import BaseModel, Field

# --- Processed Note Schema ---

class ProcessedNoteSchema(BaseModel):
    body: str = Field(..., description="AI-cleaned note content")
    key_points: List[str] = Field(default_factory=list, description="Key insights extracted")

# --- Base Schema (Common Fields) ---

class NoteBaseSchema(BaseModel):
    raw_note: str = Field(..., description="The original, raw text of the note")
    processed_note: Optional[ProcessedNoteSchema] = Field(None, description="Structured processed content")
    contact_id: uuid.UUID = Field(..., description="The ID of the contact this note is associated with")

# --- Create Schema (for POST requests) ---

class NoteCreateSchema(NoteBaseSchema):
    # user_id and created_by will be injected from auth token in the endpoint
    pass # Inherits all fields from Base

# --- Update Schema (for PATCH requests) ---

class NoteUpdateSchema(BaseModel):
    # Only allow updating specific fields, e.g., the processed note
    raw_note: Optional[str] = Field(None, description="The original, raw text of the note")
    processed_note: Optional[ProcessedNoteSchema] = Field(None, description="Structured processed content")
    # Should contact_id be updatable? Probably not.

# --- Response Schema (for GET requests) ---

class NoteResponseSchema(NoteBaseSchema):
    id: uuid.UUID # The internal ID generated by our system
    user_id: str  # The owner user ID
    created_on: datetime
    created_by: str
    updated_on: Optional[datetime] = None
    updated_by: Optional[str] = None

    class Config:
        from_attributes = True # Enable conversion from ORM/Pydantic models 