import uuid
from datetime import datetime
from typing import Optional, List, Dict, Any

from pydantic import BaseModel, Field, validator, ConfigDict

# Domain model imports (adjust path if needed)
from assiist_back_end.models.task import TaskStatus, TaskType

# --- Base Schema (Common Fields) ---

class TaskBaseSchema(BaseModel):
    contact_id: uuid.UUID = Field(..., description="The ID of the contact this task is associated with.")
    title: str
    body: Optional[str] = None
    type: TaskType
    actionable_date: Optional[datetime] = None
    due_date: Optional[datetime] = None
    status: TaskStatus = "pending"
    sms_url: Optional[str] = Field(None, description="Platform-specific SMS URL for sending the message")

# --- Create Schema (for POST requests) ---

class TaskCreateSchema(TaskBaseSchema):
    # user_id, created_by, updated_by will be injected from auth token/context
    revision_context: Optional[Dict[str, Any]] = Field(None, description="Context data for creating revision history with message tasks")

# --- Update Schema (for PATCH requests) ---

class TaskUpdateSchema(BaseModel):
    # Only allow updating specific fields
    title: Optional[str] = None
    body: Optional[str] = None
    type: Optional[TaskType] = None
    actionable_date: Optional[datetime] = None
    due_date: Optional[datetime] = None
    status: Optional[TaskStatus] = None
    sms_url: Optional[str] = None

    # contact_id should likely be immutable
    # updated_by will be set from auth token

# --- Response Schema (for GET requests) ---

class TaskResponseSchema(TaskBaseSchema):
    id: uuid.UUID # The internal ID generated by our system
    user_id: str  # The user ID associated with the task (owner/assignee)
    contact_id: Optional[uuid.UUID] # Include contact_id in response
    contact_display_name: Optional[str] = None # NEW FIELD for denormalized name
    created_on: datetime
    created_by: str # User ID of the creator
    updated_on: Optional[datetime] = None
    updated_by: Optional[str] = None # User ID of the last updater
    completed_on: Optional[datetime] = None

    class Config:
        from_attributes = True # Pydantic V2 for ORM mode 