import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:assiist_front_end/providers/reservation_providers.dart';
import 'package:assiist_front_end/core/models/contact.dart';
import 'package:assiist_front_end/core/models/reservation.dart';
import 'package:assiist_front_end/providers/auth_providers.dart';
import 'package:assiist_front_end/screens/reservation_screen.dart';
import 'package:assiist_front_end/theme/app_styles.dart';

// State notifier to manage the promo status
class PromoStatusNotifier extends StateNotifier<AsyncValue<bool>> {
  final Ref ref;
  final Contact contact;

  PromoStatusNotifier(this.ref, this.contact)
    : super(const AsyncValue.loading()) {
    _loadStatus();
  }

  Future<void> _loadStatus() async {
    try {
      final reservations = await ref.read(
        getReservationsProvider({'contactId': contact.id}).future,
      );
      state = AsyncValue.data(reservations.isNotEmpty);
    } catch (e, stack) {
      state = AsyncValue.error(e, stack);
    }
  }

  Future<void> toggleStatus() async {
    final currentStatus = state.value ?? false;
    state = const AsyncValue.loading();

    try {
      if (currentStatus) {
        // Remove from promo list
        final reservations = await ref.read(
          getReservationsProvider({'contactId': contact.id}).future,
        );
        if (reservations.isNotEmpty) {
          final success = await ref
              .read(reservationRepositoryProvider)
              .delete(reservations.first.id);
          if (success) {
            state = const AsyncValue.data(false);
          } else {
            throw Exception('Failed to remove from promo list');
          }
        }
      } else {
        // Add to promo list
        final userId = ref.read(userIdProvider);
        final accountId = ref.read(currentAccountIdProvider);

        if (userId == null || accountId == null) {
          throw Exception('User or account information not available');
        }

        final reservation = Reservation(
          id: '', // Will be generated by backend
          contactId: contact.id,
          contactName: contact.displayName,
          contactEmail: contact.emails?.firstOrNull?.address ?? '',
          contactPhone: contact.phone_numbers?.firstOrNull?.number ?? '',
          userId: userId,
          accountId: accountId,
          createdOn: DateTime.now(), // ← FIXED: Use *_on suffix
          updatedOn: DateTime.now(), // ← FIXED: Use *_on suffix
        );

        final success = await ref.read(
          addToReservationListProvider(reservation).future,
        );
        if (success) {
          state = const AsyncValue.data(true);
        } else {
          throw Exception('Failed to add to promo list');
        }
      }
    } catch (e, stack) {
      state = AsyncValue.error(e, stack);
    }
  }
}

final promoStatusProvider = StateNotifierProvider.family<
  PromoStatusNotifier,
  AsyncValue<bool>,
  Contact
>((ref, contact) => PromoStatusNotifier(ref, contact));

class ShareAssiistContactRecord extends ConsumerWidget {
  final Contact contact;
  final VoidCallback? onShare;

  const ShareAssiistContactRecord({
    Key? key,
    required this.contact,
    this.onShare,
  }) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final promoStatus = ref.watch(promoStatusProvider(contact));

    return promoStatus.when(
      data:
          (isInPromoList) => Row(
            mainAxisSize: MainAxisSize.min,
            children: [
              isInPromoList
                  ? Container(
                    decoration: BoxDecoration(
                      gradient: AppStyles.gradientAccent,
                      borderRadius: BorderRadius.circular(28.0),
                    ),
                    child: CupertinoButton(
                      padding: const EdgeInsets.symmetric(
                        vertical: 8.0,
                        horizontal: 16.0,
                      ),
                      minSize: 0,
                      borderRadius: BorderRadius.circular(28.0),
                      onPressed: () async {
                        await ref
                            .read(promoStatusProvider(contact).notifier)
                            .toggleStatus();
                        onShare?.call();
                      },
                      child: Row(
                        mainAxisSize: MainAxisSize.min,
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Icon(
                            CupertinoIcons.minus,
                            size: 18.0,
                            color: CupertinoColors.white,
                          ),
                          const SizedBox(width: 8.0),
                          const Text(
                            'Remove from Founders List',
                            style: TextStyle(
                              fontSize: 15.0,
                              fontWeight: FontWeight.w500,
                              color: CupertinoColors.white,
                            ),
                          ),
                        ],
                      ),
                    ),
                  )
                  : CupertinoButton(
                    padding: EdgeInsets.zero,
                    onPressed: () async {
                      await ref
                          .read(promoStatusProvider(contact).notifier)
                          .toggleStatus();
                      onShare?.call();
                    },
                    child: Container(
                      decoration: BoxDecoration(
                        gradient: AppStyles.gradientAccent,
                        borderRadius: BorderRadius.circular(28.0),
                      ),
                      padding: const EdgeInsets.all(1.5),
                      child: Container(
                        decoration: BoxDecoration(
                          color: AppStyles.subtleBackgroundColor(context),
                          borderRadius: BorderRadius.circular(26.5),
                        ),
                        child: Padding(
                          padding: const EdgeInsets.symmetric(
                            vertical: 6.5,
                            horizontal: 14.5,
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              AppStyles.accentIcon(
                                icon: CupertinoIcons.plus,
                                size: 18.0,
                              ),
                              const SizedBox(width: 8.0),
                              AppStyles.accentText(
                                context,
                                'Add to Founders List',
                                style: const TextStyle(
                                  fontSize: 15.0,
                                  fontWeight: FontWeight.w500,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ),
                  ),
            ],
          ),
      loading:
          () => Row(
            mainAxisSize: MainAxisSize.min,
            children: [
              CupertinoButton(
                padding: const EdgeInsets.symmetric(
                  vertical: 8.0,
                  horizontal: 16.0,
                ),
                minSize: 0,
                color: CupertinoColors.systemGrey4,
                borderRadius: BorderRadius.circular(28.0),
                onPressed: null,
                child: const SizedBox(
                  width: 18.0,
                  height: 18.0,
                  child: CircularProgressIndicator(
                    strokeWidth: 2,
                    valueColor: AlwaysStoppedAnimation<Color>(
                      CupertinoColors.white,
                    ),
                  ),
                ),
              ),
            ],
          ),
      error:
          (error, stack) => Row(
            mainAxisSize: MainAxisSize.min,
            children: [
              CupertinoButton(
                padding: const EdgeInsets.symmetric(
                  vertical: 8.0,
                  horizontal: 16.0,
                ),
                minSize: 0,
                color: CupertinoColors.systemGrey4,
                borderRadius: BorderRadius.circular(28.0),
                onPressed: () {
                  ref.read(promoStatusProvider(contact).notifier)._loadStatus();
                },
                child: const Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Icon(
                      CupertinoIcons.exclamationmark_circle,
                      size: 18.0,
                      color: CupertinoColors.white,
                    ),
                    SizedBox(width: 8.0),
                    Text(
                      'Retry',
                      style: TextStyle(
                        fontSize: 15.0,
                        fontWeight: FontWeight.w500,
                        color: CupertinoColors.white,
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
    );
  }
}

// New widget specifically for the dashboard
class DashboardShareAssiistNavBarSection extends StatelessWidget {
  final VoidCallback? onShare;
  const DashboardShareAssiistNavBarSection({Key? key, this.onShare})
    : super(key: key);

  void _handlePromoButtonPress(BuildContext context) {
    // Navigate to reservation screen
    Navigator.of(
      context,
    ).push(CupertinoPageRoute(builder: (context) => const ReservationScreen()));

    if (onShare != null) {
      onShare!();
    }
  }

  @override
  Widget build(BuildContext context) {
    return Row(
      mainAxisSize: MainAxisSize.min,
      children: [
        Container(
          decoration: BoxDecoration(
            gradient:
                AppStyles.gradientAccent, // Use gradient instead of solid color
            borderRadius: BorderRadius.circular(8.0),
          ),
          child: CupertinoButton(
            padding: const EdgeInsets.symmetric(
              vertical: 8.0,
              horizontal: 16.0,
            ),
            minSize: 0,
            borderRadius: BorderRadius.circular(8.0),
            onPressed: () => _handlePromoButtonPress(context),
            child: Row(
              mainAxisSize: MainAxisSize.min,
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                const Icon(
                  CupertinoIcons.plus,
                  size: 18.0,
                  color: CupertinoColors.white,
                ),
                const SizedBox(width: 8.0),
                const Text(
                  'Add to Founders List',
                  style: TextStyle(
                    fontSize: 15.0,
                    fontWeight: FontWeight.w500,
                    color: CupertinoColors.white,
                  ),
                ),
              ],
            ),
          ),
        ),
      ],
    );
  }
}
